// language/async: async: test_async_primitives
async fn fetchi8() -> i8 {
    return 16;
}

def MAX_I64 = 9223372036854775807;

async fn fetchi64() -> i64 {
    return MAX_I64;
}

async fn fetchchar() -> char {
    return 'B';
}

async fn fetchbool() -> bool {
    return true;
}

test "async_returns_primitives" {
    let r1 = await fetchi8();
    assert(r1 == 16, "failed to return i8");

    let r2 = await fetchi64();
    assert(r2 == MAX_I64, "failed to return i64");

    let r3 = await fetchchar();
    assert(r3 == 'B', "failed to return char");

    let r4 = await fetchbool();
    assert(r4 == true, "failed to return bool");
}