// async: test_async_string
async fn fetch_string() -> string {
    return "Hello, world!";
}

async fn fetch_charptr() -> char* {
    return "Hello, world!";
}

test "async_returns_string" {
    let result = await fetch_string();
    assert(result == "Hello, world!", "failed to return string");

    let result2 = await fetch_charptr();
    assert(strcmp(result2, "Hello, world!") == 0, "failed to return char*");
}