struct String {
    data: char*;
}

struct StringOfString {
    str: String*;
}

async fn fetch_struct() -> String {
    let str = String { data: (char*)malloc(sizeof(char) * 6) };
    strcpy(str.data, "World");
    return str;
}

async fn fetch_struct2() -> StringOfString* {
    let str_ptr: String* = (String*)malloc(sizeof(String));
    *str_ptr = await fetch_struct();
    let ptr: StringOfString* = (StringOfString*)malloc(sizeof(StringOfString));
    *ptr = StringOfString { str: str_ptr };
    return ptr;
}

test "async_returns_struct_ptr" {
    let result = await fetch_struct2();
    assert(strcmp(result.str.data, "World") == 0, "failed to return struct of struct");
}

impl Drop for String {
    fn drop(self) { free(self.data); self.data = NULL; }
}

impl Drop for StringOfString {
    fn drop(self) { self.str.drop(); self.str = NULL; }
}