struct String {
    data: char*;
}

struct StringOfString {
    str: String;
}

async fn fetch_struct() -> String {
    let str = String { data: (char*)malloc(sizeof(char) * 6) };
    strcpy(str.data, "Hello");
    return str;
}

async fn fetch_struct2() -> StringOfString {
    let str = await fetch_struct();
    return StringOfString {
        str: str
    };
}

test "async_returns_struct" {
    let result = await fetch_struct();
    assert(strcmp(result.data, "Hello") == 0, "failed to return struct");

    let result2 = await fetch_struct2();
    assert(strcmp(result2.str.data, "Hello") == 0, "failed to return struct of struct");
}

impl Drop for String {
    fn drop(self) { free(self.data); self.data = NULL; }
}