import "std/string.zc"

test "utf8_basic_ascii" {
    let s = String::from("Hello");
    
    assert(s.utf8_len() == 5, "ASCII Len failed");
    
    let h = s.utf8_at(0);
    let t1 = String::from("H");
    assert(h.eq(&t1), "ASCII At failed");
    
    let sub = s.utf8_substr(1, 4);
    let t2 = String::from("ello");
    assert(sub.eq(&t2), "ASCII Substr failed");
}

test "utf8_multibyte" {
    // "Hey 🌎!" - "Hey " (4) + 🌎 (1) + "!" (1) = 6 chars
    // Bytes: H(1) e(1) y(1)  (1) 🌎(4) !(1) = 9 bytes?
    // 🌎 is approx F0 9F 8C 8D (4 bytes)
    
    let s = String::from("Hey 🌎!");
    
    assert(s.length() == 9, "Byte length unexpected");

    assert(s.utf8_len() == 6, "UTF8 Len failed");
    
    let globe = s.utf8_at(4);
    let t3 = String::from("🌎");
    assert(globe.eq(&t3), "UTF8 At failed");
    
    let sub = s.utf8_substr(4, 2); // "🌎!"
    let t4 = String::from("🌎!");
    assert(sub.eq(&t4), "UTF8 Substr failed");
}