import plugin "plugins/brainfuck.so" as bf
//import plugin "plugins/brainfuck.dll" as bf // works on windows! Just keep your compiler consistent
import "std/io.zc"

test "dynamic plugin loading" {
    // Basic Brainfuck: prints 'A' (ASCII 65)
    // +++++ +++++ [ > +++++ + < - ] > +++++ .
    // 10 * 6 + 5 = 65
    bf! {
        ++++++++++[>++++++<-]>+++++.
    }

    println "";
    assert(true, "Plugin loaded and executed");
}
