// compiler/typecheck: typecheck: test_impl_analysis
import "std.zc"

struct Simple {
    x: int;
}

impl Drop for Simple {
    fn drop(self) {}
}

impl Simple {
    fn test_codegen(ptr: Simple*) -> bool {
        // This used to incorrectly call a custom Eq operator
        // if another type with custom Eq was in scope.
        return ptr == NULL;
    }

    fn test_analysis(self) -> int {
        let b = self;
        // let c = self.x; // USE AFTER MOVE (UNCOMMENT TO TEST COMPILER ERROR)
        return 10;
    }
}

test "impl_block_analysis" {
    let s = Simple { x: 10 };
    assert(!Simple::test_codegen(&s), "ptr should not be null");
    assert(Simple::test_codegen(NULL), "ptr should be null");
    // assert(s.test_analysis() == 10, "value should be 10");
    
    println "  impl block analysis test: Success";
}
