# OS detection and portable commands
ifeq ($(OS),Windows_NT)
    EXE = .exe
    RM = rm -rf
    MKDIR = mkdir -p
    CP = cp -af
    LN = ln -sf
    INSTALL = install
else
    EXE =
    RM = rm -rf
    MKDIR = mkdir -p
    CP = cp -af
    LN = ln -sf
    INSTALL = install
endif

# Compiler configuration
# Default: gcc
# To build with clang: make CC=clang
# To build with zig:   make CC="zig cc"
GIT_VERSION := $(shell git describe --tags --always --dirty 2>/dev/null || echo "0.1.0")
SHAREDIR ?= /usr/local/share/zenc
DEFINES = -DZEN_VERSION=\"$(GIT_VERSION)\" -DZEN_SHARE_DIR=\"$(SHAREDIR)\"
WERROR ?= 0
# TCC does not support -MMD -MP and may not search /usr/local/include
ifeq ($(findstring tcc,$(CC)),tcc)
    DEPFLAGS =
    TCC_EXTRA = -I/usr/local/include -L/usr/local/lib
else
    DEPFLAGS = -MMD -MP
    TCC_EXTRA =
endif
CFLAGS = -std=gnu11 -Wall -Wextra -Wshadow -g $(DEPFLAGS) $(TCC_EXTRA) $(if $(filter 1,$(WERROR)),-Werror,) -I./src -I./src/ast -I./src/parser -I./src/codegen -I./plugins -I./src/zen -I./src/utils -I./src/lexer -I./src/analysis -I./src/lsp -I./src/diagnostics -I./std/third-party/tre/include $(DEFINES)

# Toggle plugins
ifeq ($(NO_PLUGINS), 1)
    CFLAGS += -DZC_NO_PLUGINS
    PLUGINS =
    LIBS = -lm -lpthread
else
    LIBS = -lm -lpthread -ldl
endif

ZC_HAS_JIT ?= 1
ZC_RUN ?= ./zc
ifeq ($(ZC_HAS_JIT), 1)
    CFLAGS += -DZC_HAS_JIT
endif

TARGET = zc$(EXE)
ifeq ($(OS),Windows_NT)
    LIBS = -lws2_32
    ifeq ($(ZC_HAS_JIT), 1)
        LIBS += -ltcc
    endif
else
    ifeq ($(ZC_HAS_JIT), 1)
        LIBS += -ltcc
    endif
endif

SRCS = src/main.c \
       src/driver/driver.c \
       src/parser/parser_core.c \
       src/parser/parser_expr.c \
       src/parser/parser_stmt.c \
       src/parser/parser_type.c \
       src/parser/parser_utils.c \
       src/parser/parser_decl.c \
       src/parser/parser_struct.c \
       src/ast/ast.c \
       src/ast/primitives.c \
       src/ast/symbols.c \
       src/codegen/codegen.c \
       src/codegen/codegen_stmt.c \
       src/codegen/codegen_decl.c \
       src/codegen/codegen_main.c \
       src/codegen/codegen_utils.c \
       src/utils/emitter.c \
       src/utils/utils.c \
       src/utils/colors.c \
       src/utils/cmd.c \
       src/platform/os.c \
       src/platform/console.c \
       src/platform/dylib.c \
       src/platform/misra.c \
       src/utils/config.c \
       src/diagnostics/diagnostics.c \
       src/lexer/token.c \
       src/analysis/typecheck.c \
       src/analysis/move_check.c \
       src/analysis/const_fold.c \
       src/lsp/json_rpc.c \
       src/lsp/lsp_main.c \
       src/lsp/lsp_analysis.c \
       src/lsp/lsp_semantic.c \
       src/lsp/lsp_index.c \
       src/lsp/lsp_formatter.c \
       src/lsp/lsp_project.c \
       src/lsp/cJSON.c \
       src/zen/zen_facts.c \
       src/zen/zen_doc.c \
       src/repl/repl.c \
       src/repl/repl_highlight.c \
       src/repl/repl_readline.c \
       src/repl/repl_eval.c \
       src/repl/repl_jit.c \
       src/repl/repl_commands.c \
       src/plugins/plugin_manager.c \
       src/plugins/static_plugins.c \
       std/third-party/tre/lib/regcomp.c \
       std/third-party/tre/lib/regerror.c \
       std/third-party/tre/lib/regexec.c \
       std/third-party/tre/lib/tre-ast.c \
       std/third-party/tre/lib/tre-compile.c \
       std/third-party/tre/lib/tre-filter.c \
       std/third-party/tre/lib/tre-match-approx.c \
       std/third-party/tre/lib/tre-match-backtrack.c \
       std/third-party/tre/lib/tre-match-parallel.c \
       std/third-party/tre/lib/tre-mem.c \
       std/third-party/tre/lib/tre-parse.c \
       std/third-party/tre/lib/tre-stack.c \
       std/third-party/tre/lib/xmalloc.c

OBJ_DIR = obj
OBJS = $(patsubst %.c, $(OBJ_DIR)/%.o, $(SRCS))
DEPS = $(OBJS:.o=.d)

# Pull in header dependency files (auto-generated by -MMD -MP)
-include $(DEPS)

# Installation paths
PREFIX ?= /usr/local
BINDIR = $(PREFIX)/bin
MANDIR = $(PREFIX)/share/man
SHAREDIR = $(PREFIX)/share/zenc
INCLUDEDIR = $(PREFIX)/include/zenc

PLUGINS = plugins/befunge.so plugins/brainfuck.so plugins/forth.so plugins/lisp.so plugins/sql.so

# APE (Actually Portable Executable) configuration
COSMOCC = cosmocc
OUT_STAGE = out/stage
OUT_BIN = out/bin
ZC_ENTRY_O = $(OUT_STAGE)/zc_entry.o
ZC_COM_BIN = $(OUT_STAGE)/zc.com
ZC_COM = $(OUT_BIN)/zc.com
ZC_BOOT_SRC = ape/boot/boot.zc
ZC_BOOT_COM_BIN = $(OUT_STAGE)/zc-boot.com
ZC_BOOT_COM = $(OUT_BIN)/zc-boot.com

# Discover plugins for static linking
PLUGIN_FILES = $(wildcard plugins/*.zc)
PLUGIN_NAMES = $(patsubst plugins/%.zc,%,$(PLUGIN_FILES))
PLUGIN_APE_OBJS = $(patsubst plugins/%.zc,obj-ape/plugins/%.o,$(PLUGIN_FILES))

# Function to sanitize plugin names for C identifiers
# Usage: $(call sanitize_name,name)
sanitize_name = $(shell echo $(1) | sed 's/[^a-zA-Z0-9]/_/g')

# Default target
all: $(TARGET) $(PLUGINS)

# APE target
ape: $(ZC_COM) $(ZC_BOOT_COM)

# Build plugins

plugins/%.so: plugins/%.zc $(TARGET)
	$(ZC_RUN) build $< -shared -o $@

# Link
$(TARGET): $(OBJS)
	@$(MKDIR) $(dir $@)
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)
	@echo "=> Build complete: $(TARGET)"

# Compile
$(OBJ_DIR)/%.o: %.c
	@$(MKDIR) $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

# APE targets
$(ZC_ENTRY_O): ape/zc_entry.c
	@$(MKDIR) $(@D)
	$(COSMOCC) -c $< -o $@

$(ZC_COM_BIN): $(ZC_ENTRY_O) $(SRCS) src/plugins/static_plugins.c $(PLUGIN_APE_OBJS)
	@$(MKDIR) $(@D)
	$(MAKE) \
		PLUGINS= \
		ZC_HAS_JIT=0 \
		CC=$(COSMOCC) \
		OBJ_DIR=obj-ape \
		DEFINES='$(DEFINES) -DZC_STATIC_PLUGINS' \
		LIBS="$(abspath $(ZC_ENTRY_O)) $(PLUGIN_APE_OBJS) -Wl,--wrap=main" \
		SRCS="$(SRCS) src/plugins/static_plugins.c" \
		TARGET="$(abspath $@)";

src/plugins/static_plugins.c: $(PLUGIN_FILES)
	@echo "=> Generating static plugin registry: $@"
	@echo '#include "plugin_manager.h"' > $@
	@echo '#include <string.h>' >> $@
	@echo '#ifdef ZC_STATIC_PLUGINS' >> $@
	@for p in $(PLUGIN_NAMES); do \
		psafe=$$(echo $$p | sed 's/[^a-zA-Z0-9]/_/g'); \
		echo "extern ZPlugin *z_plugin_init_$$psafe(void);" >> $@; \
	done
	@echo 'ZPlugin *zptr_get_static_plugin(const char *name) {' >> $@
	@for p in $(PLUGIN_NAMES); do \
		psafe=$$(echo $$p | sed 's/[^a-zA-Z0-9]/_/g'); \
		echo "  if (strcmp(name, \"$$p\") == 0 || strcmp(name, \"plugins/$$p\") == 0) return z_plugin_init_$$psafe();" >> $@; \
	done
	@echo '  return NULL;' >> $@
	@echo '}' >> $@
	@echo '#else' >> $@
	@echo 'ZPlugin *zptr_get_static_plugin(const char *name) { (void)name; return NULL; }' >> $@
	@echo '#endif' >> $@

obj-ape/plugins/%.c: plugins/%.zc $(TARGET)
	@$(MKDIR) $(@D)
	./$(TARGET) transpile $< -o $@

obj-ape/plugins/%.o: obj-ape/plugins/%.c
	@$(MKDIR) $(@D)
	@psafe=$$(echo $* | sed 's/[^a-zA-Z0-9]/_/g'); \
	$(COSMOCC) $(CFLAGS) -DZC_STATIC_PLUGIN -Dz_plugin_init=z_plugin_init_$$psafe -c $< -o $@

$(ZC_COM): $(ZC_COM_BIN)
	@$(MKDIR) $(@D)
	@$(CP) $(ZC_COM_BIN) $(wildcard $(ZC_COM_BIN).*) "$(@D)"; \
	cp src/misc/zenc.json zenc.json; \
	cp src/zen/facts.json facts.json; \
	cp src/repl/docs.json docs.json; \
	zip -r "$(abspath $@)" std.zc std LICENSE zenc.json facts.json docs.json; \
	rm -f zenc.json facts.json docs.json

$(ZC_BOOT_COM_BIN): $(ZC_BOOT_SRC) $(ZC_COM)
	@$(MKDIR) $(@D)
	./$(ZC_COM) build --cc $(COSMOCC) -o $@ $<

$(ZC_BOOT_COM): $(ZC_BOOT_COM_BIN) ape/boot/.args
	@$(MKDIR) $(@D)
	@$(CP) $(ZC_BOOT_COM_BIN) $(wildcard $(ZC_BOOT_COM_BIN).*) "$(@D)"; \
	cp src/misc/zenc.json zenc.json; \
	cp src/zen/facts.json facts.json; \
	cp src/repl/docs.json docs.json; \
	(cd ape/boot && zip "$(abspath $@)" .args hello.zc instructions.txt Makefile); \
	zip "$(abspath $@)" LICENSE zenc.json facts.json docs.json; \
	rm -f zenc.json facts.json docs.json

# Install
install: $(TARGET)
	$(INSTALL) -d $(BINDIR)
	$(INSTALL) -m 755 $(TARGET) $(BINDIR)/$(TARGET)
	
	# Install man pages
	$(INSTALL) -d $(MANDIR)/man1 $(MANDIR)/man5 $(MANDIR)/man7
	test -f man/zc.1 && $(INSTALL) -m 644 man/zc.1 $(MANDIR)/man1/zc.1 || true
	test -f man/zc.5 && $(INSTALL) -m 644 man/zc.5 $(MANDIR)/man5/zc.5 || true
	test -f man/zc.7 && $(INSTALL) -m 644 man/zc.7 $(MANDIR)/man7/zc.7 || true
	test -f man/zc-stdlib.7 && $(INSTALL) -m 644 man/zc-stdlib.7 $(MANDIR)/man7/zc-stdlib.7 || true
	
	# Install standard library
	$(INSTALL) -d $(SHAREDIR)
	$(INSTALL) -m 644 std.zc $(SHAREDIR)/std.zc
	$(CP) std $(SHAREDIR)/
	
	# Install facts
	$(INSTALL) -m 644 src/zen/facts.json $(SHAREDIR)/facts.json
	$(INSTALL) -m 644 src/repl/docs.json $(SHAREDIR)/docs.json
	$(INSTALL) -m 644 src/misc/zenc.json $(SHAREDIR)/zenc.json
	
	# Install plugin headers
	$(INSTALL) -d $(INCLUDEDIR)
	$(INSTALL) -m 644 plugins/zprep_plugin.h $(INCLUDEDIR)/zprep_plugin.h
	
	# Install compiled plugins
	$(INSTALL) -d $(SHAREDIR)/plugins
	$(CP) plugins/*.so $(SHAREDIR)/plugins/
	@echo "=> Installed to $(BINDIR)/$(TARGET)"
	@echo "=> Man pages installed to $(MANDIR)"
	@echo "=> Standard library installed to $(SHAREDIR)/std"

# Uninstall
uninstall:
	$(RM) $(BINDIR)/$(TARGET)
	$(RM) $(MANDIR)/man1/zc.1
	$(RM) $(MANDIR)/man5/zc.5
	$(RM) $(MANDIR)/man7/zc.7
	$(RM) $(MANDIR)/man7/zc-stdlib.7
	$(RM) $(SHAREDIR)
	@echo "=> Uninstalled from $(BINDIR)/$(TARGET)"
	@echo "=> Removed man pages from $(MANDIR)"
	@echo "=> Removed $(SHAREDIR)"

# Install APE
install-ape: ape
	$(INSTALL) -d $(BINDIR)
	$(INSTALL) -m 755 $(ZC_COM) $(BINDIR)/zc.com
	$(INSTALL) -m 755 $(ZC_BOOT_COM) $(BINDIR)/zc-boot.com
	$(LN) $(BINDIR)/zc.com $(BINDIR)/zc
	
	# Install standard library (shared)
	$(INSTALL) -d $(SHAREDIR)
	$(INSTALL) -m 644 std.zc $(SHAREDIR)/std.zc
	$(CP) std $(SHAREDIR)/
	@echo "=> Installed APE binaries to $(BINDIR)"
	@echo "=> Alias 'zc' points to zc.com"
	@echo "=> Standard library installed to $(SHAREDIR)/std"

# Uninstall APE
uninstall-ape:
	$(RM) $(BINDIR)/zc
	$(RM) $(BINDIR)/zc.com
	$(RM) $(BINDIR)/zc-boot.com
	$(RM) $(SHAREDIR)
	@echo "=> Uninstalled APE binaries from $(BINDIR)"
	@echo "=> Removed $(SHAREDIR)"

# Clean
clean:
	$(RM) $(OBJ_DIR) obj-ape obj-fuzz obj-fuzz-cmplog $(TARGET) out.c out.cpp out.m plugins/*.so a.out* out test_out_* rule_*
	@echo "=> Clean complete!"

# Code Formatting
CLANG_FORMAT ?= clang-format
SRC_FILES = $(filter %.c %.h, $(shell find src -type f \( -name '*.c' -o -name '*.h' \)))

format:
	$(CLANG_FORMAT) -i $(SRC_FILES)
	@echo "=> Formatted $(words $(SRC_FILES)) source files"

format-check:
	$(CLANG_FORMAT) --dry-run --Werror $(SRC_FILES)
	@echo "=> All source files are properly formatted"

# Linting
lint: format-check
	@echo "=> Running shellcheck on test scripts"
	-shellcheck tests/scripts/*.sh
	@echo "=> Lint complete"

# Benchmarks
bench: $(TARGET)
	./tests/scripts/run_benchmarks.sh

# Test
# Supports running specific tests:
#	make test only="tests/std/test_hash.zc examples/arena_test.zc"
test: $(TARGET) $(PLUGINS)
	./tests/scripts/run_tests.sh -- $(filter %.zc,$(only))
	./tests/scripts/run_codegen_tests.sh $(filter %.zc,$(only))
	./tests/scripts/run_example_transpile.sh $(filter %.zc,$(only))
	$(MAKE) test-misra

test-misra: $(TARGET)
	./tests/scripts/run_misra_tests.sh

test-tcc: $(TARGET) $(PLUGINS)
	./tests/scripts/run_tests.sh --cc tcc

test-lsp: $(TARGET) $(PLUGINS)
	@echo "=> Building LSP Test Runner"
	$(CC) $(CFLAGS) -DZC_NO_ARENA tests/compiler/lsp/lsp_test_runner.c src/lsp/cJSON.c -o tests/compiler/lsp/test_runner
	@echo "=> Running LSP Tests"
	./tests/compiler/lsp/test_runner

# Build with alternative compilers
zig:
	$(MAKE) CC="zig cc"

clang:
	$(MAKE) CC=clang

windows:
	$(MAKE) CC="x86_64-w64-mingw32-gcc" TARGET="zc.exe" UI_OS="Windows" LIBS="-static -lm -lpthread"

asan: CFLAGS += -fsanitize=address,undefined -O1 -fno-omit-frame-pointer
asan: LIBS += -fsanitize=address,undefined
asan: ZC_RUN = ASAN_OPTIONS=detect_leaks=0 ./zc
asan: $(TARGET) $(PLUGINS)

test-asan: clean asan
	ASAN_OPTIONS=detect_leaks=0 ./tests/scripts/run_tests.sh
	ASAN_OPTIONS=detect_leaks=0 ./tests/scripts/run_codegen_tests.sh
	ASAN_OPTIONS=detect_leaks=0 ./tests/scripts/run_example_transpile.sh

test-plugins: $(TARGET) $(PLUGINS)
	./zc run tests/plugins_suite.zc

# Fuzzing
FUZZ_TARGET = zc-fuzz
FUZZ_CMPLOG_TARGET = zc-fuzz-cmplog
FUZZ_CC ?= afl-clang-fast
FUZZ_DIR = fuzz
FUZZ_OUT = $(FUZZ_DIR)/out
FUZZ_CORPUS = $(FUZZ_DIR)/corpus
FUZZ_DICT = $(FUZZ_DIR)/zen_c.dict

# High-performance flags
FUZZ_CFLAGS = -O3 -march=native -D__AFL_HAVE_MANUAL_CONTROL

fuzz-build:
	@$(MKDIR) $(OBJ_DIR)/fuzz
	$(MAKE) CC=$(FUZZ_CC) CFLAGS='$(CFLAGS) $(FUZZ_CFLAGS)' OBJ_DIR=obj-fuzz TARGET=$(FUZZ_TARGET) SRCS="$(filter-out src/main.c,$(SRCS)) fuzz/harness.c"
	@echo "=> Fuzzing target built (Persistent Mode): $(FUZZ_TARGET)"

fuzz-cmplog-build:
	@$(MKDIR) $(OBJ_DIR)/fuzz-cmplog
	AFL_LLVM_CMPLOG=1 $(MAKE) CC=$(FUZZ_CC) CFLAGS='$(CFLAGS) $(FUZZ_CFLAGS)' OBJ_DIR=obj-fuzz-cmplog TARGET=$(FUZZ_CMPLOG_TARGET) SRCS="$(filter-out src/main.c,$(SRCS)) fuzz/harness.c"
	@echo "=> CmpLog target built: $(FUZZ_CMPLOG_TARGET)"

# LibFuzzer targets
fuzz-libfuzzer-build:
	@$(MKDIR) $(OBJ_DIR)/fuzz-libfuzzer
	clang $(CFLAGS) -fsanitize=fuzzer,address,undefined $(filter-out src/main.c,$(SRCS)) fuzz/harness.c -o zc-fuzz-libfuzzer $(LIBS)
	@echo "=> LibFuzzer target built: zc-fuzz-libfuzzer"

fuzz-corpus:
	@$(MKDIR) $(FUZZ_CORPUS)
	@cp tests/*.zc $(FUZZ_CORPUS)/ 2>/dev/null || true
	@cp tests/std/*.zc $(FUZZ_CORPUS)/ 2>/dev/null || true
	@echo "=> Seed corpus created from existing tests"

fuzz-run: fuzz-build
	@if [ ! -d "$(FUZZ_CORPUS)" ]; then sh $(FUZZ_DIR)/scripts/generate_corpus.sh; fi
	@$(MKDIR) $(FUZZ_OUT)
	@echo "-> Starting fuzzer (Persistent Mode enabled)"
	@echo "-> Tip: For parallel runs, use '-M main' and '-S secondaryN'"
	AFL_SKIP_CPUFREQ=1 AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1 afl-fuzz -i $(FUZZ_CORPUS) -o $(FUZZ_OUT) -x $(FUZZ_DICT) -- ./$(FUZZ_TARGET)

fuzz-clean:
	rm -rf $(FUZZ_OUT)/*
	rm -f $(FUZZ_TARGET) $(FUZZ_CMPLOG_TARGET)
	rm -rf obj-fuzz obj-fuzz-cmplog

.PHONY: all clean install uninstall install-ape uninstall-ape format format-check lint bench test test-misra test-tcc test-lsp test-asan test-plugins zig clang ape windows asan fuzz-build fuzz-run fuzz-clean