// test_hash
import "std/hash.zc"

test "test_hash" {
    assert(hash_get_seed() == __zen_hash_seed, "hash_get_seed differs from __zen_hash_seed");
    
    hash_set_seed(42);

    assert(hash_get_seed() == 42, "hash_get_seed not set by hash_set_seed");
    assert(__zen_hash_seed == 42, "__zen_hash_seed not set by hash_set_seed");

    let i: int = 512;
    let hash = hash_compute(&i, sizeof(int));
    assert(hash != 0, "hash_compute returned zero");

    hash = hash_combine(10, 20);
    assert(hash != 0, "hash_combine returned zero");
}