// language/features/enums: _sockaddr_mod  --  helper module
extern struct sockaddr;

// Mocking to make it compile for the mangling test
extern let af_inet: int;
extern let NULL: void*;

namespace ws2 {
    extern fn WSAStringToAddressA(addr_str: string, af: int, p: void*, sa: void*, size: void*);
}

impl sockaddr {
   fn init (self, addr_str: string) {
      let sa_size = 16;
      ws2::WSAStringToAddressA (addr_str, af_inet, NULL, self, (int*) &sa_size);
   }
   fn new () -> sockaddr* {
      return (sockaddr*) NULL;
   }
}
