
struct Foo<T> {
  value: T;
}

impl Foo<T> {
  fn eq(self, other: Foo<T>) -> bool {
    return self.value == other.value;
  }
  fn neq(self, other: Foo<T>) -> bool {
    return !(self == other);
  }
}

test "generic neq" {
  let f1 = Foo<i32>{value: 10};
  let f2 = Foo<i32>{value: 20};
  assert(f1 != f2, "f1 should not equal f2");

  let f3 = Foo<i32>{value: 10};
  let f4 = Foo<i32>{value: 10};
  assert(f3 == f4, "f3 should equal f4");
  
  let f5 = Foo<i32>{value: 10};
  let f6 = Foo<i32>{value: 10};
  assert(!(f5 != f6), "f5 != f6 should be false");
}
