
// 5-tuple tests

fn five_tuple() -> (int, int, int, int, int) {
    return (1, 2, 3, 4, 5);
}

test "5-tuple return" {
    let t = five_tuple();
    assert(t.0 == 1, "0");
    assert(t.1 == 2, "1");
    assert(t.2 == 3, "2");
    assert(t.3 == 4, "3");
    assert(t.4 == 5, "4");
}

test "5-tuple literal" {
    let t = ("a", "b", "c", "d", "e");
    assert(t.0 == "a" && t.4 == "e", "5-tuple strings");
}
