name: Zen-C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-15-intel, ubuntu-24.04, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
      if: matrix.os != 'windows-2025'
    - name: make test
      run: make test
      if: matrix.os != 'windows-2025'
    - uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-2025'
    - name: build on windows
      run: cmake . -G "NMake Makefiles" && cmake --build .
      if: matrix.os == 'windows-2025'
    - name: test on windows
      run: tests\run_tests.cmd --cc cl
      if: matrix.os == 'windows-2025'
