
import "example_math.h" as m;

test "test_c_import" {
    let x = m::sin(0.0);
    
    if x == 0.0 {
        println "Success: m::sin(0.0) == 0.0";
    } else {
        println "Failure: Unexpected result";
        exit(1);
    }
    }
}

extern fn abs(x: int) -> int;

test "test_interop_abs" {
    let x = -10;
    let y = abs(x);
    if (y == 10) println "Abs works";
    else {
        println "Abs failed";
        exit(1);
    }
}
